# Generated by Django 2.1.5 on 2019-01-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_datae',
            new_name='created_date',
        ),
    ]
